default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  password:
  pool: 5
  port: 5432
  username: vagrant

development:
  <<: *default
  database: coderwall_development

test:
  <<: *default
  database: coderwall_test

production:
  <<: *default
  database: coderwall_production
